### ISSUE TITLE
Please, add solc to path

### ISSUE THREAD

**Issue by mesqueeb** [OpenZeppelin/solidity-docgen#13]
I did
```
npm install --save-dev solidity-docgen
./node_modules/.bin/solidity-docgen ./ ./contracts ./docs
```
And got:

> throw new Error(['Solidity compiler not found. Please, add solc to path or', 'define environment variable SOLC_PATH.'].join(' '));
    ^
> Error: Solidity compiler not found. Please, add solc to path or define environment variable SOLC_PATH.

I'm not sure what they mean with **"add to path"**.

**Comment by mesqueeb** [comment]
After this I've also tried
```
npm install --save-dev openzeppelin-solidity
env SOLC_ARGS='openzeppelin-solidity=./node_modules/openzeppelin-solidity' ./node_modules/.bin/solidity-docgen ./ ./contracts ./docs
```
But same error.

**Comment by Aniket-Engg** [comment]
Make sure you have installed `solc` on your system.
Run `which solc` , you will get a path like this : `/usr/bin/solc`
Run, `export SOLC_PATH = /usr/bin/solc` 
Now run the final command.

**Comment by Aniket-Engg** [comment]
@mesqueeb Have you got it worked?

**Comment by mesqueeb** [comment]
Sorry i have this on my to do list. I will reply when i checked!!!

**Comment by sohkai** [comment]
@spalladino would it be possible for this module to use `solcjs` instead of the native compiler? It could even be set as a peer dependency.

**Comment by spalladino** [comment]
Hey Brett! That's a good idea, but I don't have the time to work on that now. Do you think you could send a PR? I'd be happy to review it!

**Comment by maxsam4** [comment]
@sohkai We were in the same dilema and as a quick alternative, I just modified our script to fetch the needed binary from gh and update paths. Relevant code snippet:
```
curl -L -o solidity-ubuntu-trusty.zip https://github.com/ethereum/solidity/releases/download/v0.4.24/solidity-ubuntu-trusty.zip
unzip solidity-ubuntu-trusty.zip
CWD=$(pwd)
OLD_SOLC_PATH=$SOLC_PATH
export SOLC_PATH=$CWD/solc
# solidity-docgen command
export SOLC_PATH=$OLD_SOLC_PATH
```
full code: https://github.com/PolymathNetwork/polymath-core/blob/docs-solc-fix/scripts/docs.sh

**Comment by sohkai** [comment]
Cool @maxsam4! Partly the reason this came up was because I can't install solc on macOS14 ;).

@spalladino I likely won't have a lot time to take a look for a few weeks, but I'll take a peek and see if it's easily doable.

**Comment by ealmansi** [comment]
@spalladino @sohkai 

I originally intended to use [solcjs](https://github.com/ethereum/solc-js) instead of [solc](https://github.com/ethereum/solidity) since it would greatly simplify the installation process and usage for this project. However, the command-line interface for solcjs seems to be significantly more limited than the one provided by solc. After spending some time on it, I only managed to get full ASTs including documentation and comments from solc, and not from solcjs.

Compare the command-line interfaces of [solcjs](https://gist.github.com/ealmansi/edaa72e60f8f3050c6dc0eaf85877c35) and [solcjs](https://gist.github.com/ealmansi/932377cbc63c2b29cf539b789eac6aab).

To clarify what information solidity-docgen needs from the compiler, I add an example below.

When the following command is run:

```
SOLC_ARGS='openzeppelin-solidity=/tmp/some-project/node_modules/openzeppelin-solidity' \
solidity-docgen /tmp/some-project/ /tmp/some-project/contracts/ /tmp/some-project/docs/
```

solidity-docgen issues the following command to the shell for each contract in the contracts directory:

```
solc --pretty-json --allow-paths /tmp/project/contracts --combined-json abi,ast,compact-format,devdoc,hashes,interface,metadata,opcodes,srcmap,srcmap-runtime,userdoc openzeppelin-solidity=/tmp/project/node_modules/openzeppelin-solidity /tmp/project/contracts/Contract.sol
```

The properties provided to the argument "combined-json" specify what information the compiler is supposed to output. I did not find a way to get the same information - which is used to create the contracts' documentation pages - from solcjs.

**Comment by touchkino** [comment]
It's working for me. I just added command (pwd). 
`package.json`
```
...

  "scripts": {
    "docgen": "SOLC_ARGS='openzeppelin-solidity=`pwd`/node_modules/openzeppelin-solidity' node_modules/.bin/solidity-docgen . ./contracts ./docs"  
  },

...
```

**Comment by frangio** [comment]
The project was rewritten and it is now using solcjs no w. See v0.2 to learn about the new version, which is still in alpha.

It was brought up in #17 that solcjs doesn't work for all projects so we will probably support native solc as well in the future.

**Comment by nolanjacobson** [comment]
```brew update
brew upgrade
brew tap ethereum/ethereum
brew install solidity@5```

My issue was resolved as the npm `solc` package doesn't target `solc` but rather `solc-js`. 

Subsequently, I added solc to my PATH via `export PATH=$PATH:/usr/local/bin/solc`
