### ISSUE TITLE
Add support for Solidity 0.6 syntax

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/solidity-docgen#133]
The current release crashes when compiling 0.6 code. I suspect we'll also need to account for the new 'fallback' functions (`receive` and `fallback`) and the `virtual` attribute.

**Comment by frangio** [comment]
It crashes because it depends on the 0.5 compiler directly.

My suggestion is that we release a new minor version updating that dependency to 0.6 and stop supporting 0.5. Ideally in the future we would have a way to delegate compilation to whatever environment the user is in. But supporting multiple version is potentially complicated so it should be left for later.

To upgrade the compiler and have things work we will have to check that whether any breaking changes were introduced to the AST. Unfortunately docgen doesn't yet have any tests using the compiler, there's only unit tests for other parts of the codebase. It would be nice to add an integration test as part of this upgrade, to make sure it's smooth.

In case there were any breaking changes to the AST, there is already code in place to make an 0.4 AST look like a 0.5 AST (it changes a `function Contract()` node into a `constructor()` node), so it would be a matter of adding a new section to that adapter.

https://github.com/OpenZeppelin/solidity-docgen/blob/40341d0d1a1f859de5f28d947b5aa021a5850d47/src/compile.ts#L63

For everything related to `override`, etc., we don't need to add any special support for that initially. They will be probably be new AST properties but they just wouldn't be exposed in docgen's API. We can add them later.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/solidity-docgen/commit/087103120d419de2c44fdc6a79cb99d88f26bd3b and subsequent commits. Released in 0.4.0.
