### ISSUE TITLE
Resolve @inheritdoc tag 

### ISSUE THREAD

**Issue by mr-ubik** [OpenZeppelin/solidity-docgen#225]
NatSpec `@inheritdoc` seems to not be resolved the parser.

**Comment by abcoathup** [comment]
Hi @mr-ubik!  I’m sorry that you had this issue.  

Thanks so much for reporting it! The project owner will review and triage this issue as soon as they can.

**Comment by frangio** [comment]
I'd love to have support for `@inheritdoc`. It will require somewhat nontrivial changes and I don't expect to have availability to work on this for some time.

If someone would like to have a shot at this, here's some pointers:

- We have a `parseNatSpec` function that will now need to handle `inheritdoc` tags.
- In order to process `inheritdoc` we need to be able to resolve a contract identifier relative to a file. `parseNatSpec` is used in the `SourceContractItem` class, which can access the file that contains it through `this.contract.file`.
- We need a way to resolve contract identifiers given a `SourceFile` instance. This is where it likely will get complex. Identifiers can come from local contract definitions or, more likely, from import directives. In the case of import directives we likely will have to fetch the `SourceFile` object from the parent `Source`.

**Comment by Yorkemartin** [comment]
Just wanted to check in on this - @inheritdoc is still unsupported?

**Comment by frangio** [comment]
@Yorkemartin Yes, we haven't implemented it yet. Are you using solidity-docgen and would like to see inheritdoc supported?

**Comment by Yorkemartin** [comment]
@frangio I am using it - would love to see inheritdoc supported.

**Comment by frangio** [comment]
I can't promise any timeline, but I'll keep this in mind. If you happen to be interested in contributing the feature I'd be happy to guide you through it!

**Comment by frangio** [comment]
@mr-ubik @Yorkemartin I've implemented support for `@inheritdoc`. It's included in the latest release.

Try out and let me know if you find any issues with it!
