### ISSUE TITLE
v0.2

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/solidity-docgen#23]
The first version of `solidity-docgen` (v0.1) was coupled to Docusaurus, inherited its quirks, and was very cumbersome to set up and use. Moreover, we don't think the format of the documentation generated was as useful as it could be.

The new version is decoupled from Docusaurus and can can be integrated in any website generation pipeline. It processes Solidity source files and produces Markdown files.

Additionally, this new version takes a different approach to the structure of documentation by grouping related contracts into one page, as seen in the [upcoming OpenZeppelin v2.3 documentation](https://openzeppelin-docs-next.netlify.com/api/token/erc20).

We've implemented a rough first version of it, which will be in use starting with OpenZeppelin v2.3, but it still needs a lot of work. Contributions will be highly appreciated! We'll be documenting the work that needs to be done as issues in this repository, so anyone interested can join development and contribute. Let us know if you have any questions about it here.

**Comment by Aniket-Engg** [comment]
I think right side bar categorisation needs a bit better formatting. In most cases, it is divided in contracts, interfaces, utils, library etc and in some case ([crowdsale](https://openzeppelin-docs-next.netlify.com/api/crowdsale) one), bar is categorised in according to the use-case.

I think we should follow one pattern and in case we prefer solidity based abstract level categorisation, we also need to add a category of `abstract contract` as in some cases due to interface inheritance, we have to declare interface as contract.

**Comment by frangio** [comment]
Great point @Aniket-Engg! `solidity-docgen` itself is agnostic to the categorization chosen. This should be fixed in the main repository. I've opened https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1730 for it.

**Comment by frangio** [comment]
Closing this as this version has matured quite a bit by now.
