### ISSUE TITLE
Contracts that define/use global structs aren't documented

### ISSUE THREAD

**Issue by yudilevi** [OpenZeppelin/solidity-docgen#241]
For example, no doc is generated for this one -
https://github.com/bancorprotocol/contracts-solidity/blob/master/solidity/contracts/utility/Types.sol

In addition, contracts that use the global struct also don't get docs generated for them.

**Comment by frangio** [comment]
Thank you for reporting @yudilevi!

Structs aren't documented even when they're defined inside a contract or library. I agree that it would be a good idea to document them though. 

>contracts that use the global struct also don't get docs generated for them.

What do you mean by this?

**Comment by yudilevi** [comment]
Hey @frangio - you're right about structs - the main issue is the contracts that use them.
Take the following contract as an example -
https://github.com/bancorprotocol/contracts-solidity/blob/master/solidity/contracts/converter/types/liquidity-pool-v1/LiquidityPoolV1Converter.sol

Because it relies on the global struct from the `Types` contract, it doesn't get docs generated for it.

**Comment by frangio** [comment]
From my understanding of how `solidity-docgen` works, I fail to see how using a global struct would result in docs not being generated for the contract. I could be mistaken, though. What makes you think that it's the use of the struct that is causing this?

Can you tell me what command you're running and where, so that I can try to reproduce it locally. Thanks!

**Comment by yudilevi** [comment]
@frangio forget it - I just checked - it was a different issue and not in docgen lib - feel free to close this issue.

Thanks!
