### ISSUE TITLE
docgen does not parse @param or @return when using yarn 

### ISSUE THREAD

**Issue by Yorkemartin** [OpenZeppelin/solidity-docgen#262]
I read this feature was enabled, but it's not working for me. could using yarn be the issue? or is there some part of the config process that needs to specifically enable @param and @return parsing?

**Comment by frangio** [comment]
Hi, you're likely using [the default template](https://github.com/OpenZeppelin/solidity-docgen/blob/master/templates/contract.hbs) which does not include param and return tags.

Copy this file into your project and customize it. You can use you custom template with the option `-t <template directory>`. The directory should be the directory where `contract.hbs` is located.

In order to print `@param` and `@return` tags you would have to add something like the following:

```handlebars
{{#each natspec.params}}
{{param}}: {{description}}
{{/each}}
```

This would go inside the `{{#each ownFunctions}}` block in order to print the params of each function. The same goes for `natspec.returns`.

**Comment by frangio** [comment]
Let me know if you get it working or need any more help!

**Comment by Yorkemartin** [comment]
This is great - got that working. If there are any tips on configuring or guides it would be great to link them in the readme. not sure if the configuration adheres to some standard or if its created specifically for docgen

**Comment by frangio** [comment]
Unfortunately I haven't been able to put together a guide or reference documentation yet.

The values available in the template are defined in [this TypeScript file](https://github.com/OpenZeppelin/solidity-docgen/blob/4c1d1552a69fa182fc2a94bc6044ac20a328a604/src/source.ts). The top level is a [`SourceContract`](https://github.com/OpenZeppelin/solidity-docgen/blob/4c1d1552a69fa182fc2a94bc6044ac20a328a604/src/source.ts#L71) instance.

**Comment by Yorkemartin** [comment]
Curious about the reasoning behind filtering out private functions from the docgen? would you recommend deleting that filter in the source.ts file to generate private function docs or is there a more elegant approach?
