### ISSUE TITLE
Docs don't include structs

### ISSUE THREAD

**Issue by ichub** [OpenZeppelin/solidity-docgen#266]
I'm trying to generate documentation from my contracts, and it looks like the structs are not included in the generated documentation.

Are there plans to include structs? If not, would it be possible for you to let me know how to set up a development environment to make a PR that adds struct information to the generated documentation?

Thanks!

**Comment by frangio** [comment]
Thanks for the suggestion! One of the issues with structs is that solc doesn't parse NatSpec comments on them, so we would only be able to provide basic information about the type: name, and type and name for each member.

We don't have plans for it but it's something I would be interested in.

In order to make a PR you should fork this repo, clone the fork on your computer, and run `npm install`. You will have to add a function in [`SourceContract`](https://github.com/OpenZeppelin/solidity-docgen/blob/3ae90a54c19f8fe2bdd843fdd55c16e5b5c73c7d/src/source.ts#L106) that would be called `ownStructs`. You will need to define a new type for the AST node `StructDefinition` in `solc.ts` and add it as an option to [`ContractItem`](https://github.com/OpenZeppelin/solidity-docgen/blob/3ae90a54c19f8fe2bdd843fdd55c16e5b5c73c7d/src/solc.ts#L49). You can use [this page](https://solidity-ast.netlify.app/interfaces/structdefinition) as a reference of what fields are available in the node.

Let me know if you want to work on this. Feel free to submit a Draft PR if you need any more help.

**Comment by ichub** [comment]
I see, thanks for your reply! I'll see if there's anything I can help with at some point. It would be really great to have all of our documentation generated from source.

**Comment by KlimMixer** [comment]
> Thanks for the suggestion! One of the issues with structs is that solc doesn't parse NatSpec comments on them, so we would only be able to provide basic information about the type: name, and type and name for each member.
> 
> We don't have plans for it but it's something I would be interested in.
> 
> In order to make a PR you should fork this repo, clone the fork on your computer, and run `npm install`. You will have to add a function in [`SourceContract`](https://github.com/OpenZeppelin/solidity-docgen/blob/3ae90a54c19f8fe2bdd843fdd55c16e5b5c73c7d/src/source.ts#L106) that would be called `ownStructs`. You will need to define a new type for the AST node `StructDefinition` in `solc.ts` and add it as an option to [`ContractItem`](https://github.com/OpenZeppelin/solidity-docgen/blob/3ae90a54c19f8fe2bdd843fdd55c16e5b5c73c7d/src/solc.ts#L49). You can use [this page](https://solidity-ast.netlify.app/interfaces/structdefinition) as a reference of what fields are available in the node.
> 
> Let me know if you want to work on this. Feel free to submit a Draft PR if you need any more help.

Hi.
I have been blocked by this issue, and I have solved it.
Please review my PR: #310 
Thank you.
