### ISSUE TITLE
vyper support

### ISSUE THREAD

**Issue by steffenix** [OpenZeppelin/solidity-docgen#291]
I would be interested to know how to generate doc for both solidity and vyper files.
I guess the easiest would be to be able to do it using https://github.com/OpenZeppelin/solidity-docgen/issues/28

Another idea would to make this project importable and export some of the class like SourceContract so that can be used to build a small script that will generate the doc from the output value.

**Comment by frangio** [comment]
Hi @steffenix. I think `solidity-docgen` is too coupled to Solidity for this to make sense. What the code essentially does is traverse the Solidity AST, and the classes like `SourceContract` work on Solidity AST nodes, so exposing these classes wouldn't help at all.

In order to support Vyper the project would need drastic changes, if not a complete rewrite. It might be better to build something else from scratch to suit your needs.

Can you explain how #28 would help?

**Comment by steffenix** [comment]
I misunderstood and tough vyper output and solc output would be the in the same format.

**Comment by frangio** [comment]
Got it. I will close this issue then.

**Comment by Pzixel** [comment]
> What the code essentially does is traverse the Solidity AST, and the classes like SourceContract work on Solidity AST nodes, so exposing these classes wouldn't help at all.

I thought it's working via `solc --userdoc,devdoc`. So it uses its own contracts parser?

**Comment by frangio** [comment]
@Pzixel It uses solc to parse the AST, and the NatSpec is parsed from from the AST. See https://github.com/OpenZeppelin/solidity-docgen/issues/284#issuecomment-801333520.

**Comment by Pzixel** [comment]
Hm, okay. I've just got an impression that you parse AST yourself. If you're calling solc to do whatever parsing then it's irreleant: it's just a blackbox that get some contract as input and output some documentation jsons, and then you process those jsons. If it's now how it works then please could you be in more details?

**Comment by frangio** [comment]
I don't understand the question. Can you open a new issue?
