### ISSUE TITLE
html ouputs

### ISSUE THREAD

**Issue by rosulucian** [OpenZeppelin/solidity-docgen#37]
Do the html outputs work? 

I managed to eventually run the tool with the `--solc-module="node_modules\solc"` but the only output i get is md files and I could not find a way of generating html

**Comment by frangio** [comment]
Hey there. The recommended usage is to render markdown that you can then deploy as an HTML site using a site generator like Jekyll. Are you familiar with site generators?

Regardless, if you would like to render as HTML you can do this by defining a custom Handlebars template and using the `--templates` CLI flag.

**Comment by rosulucian** [comment]
Hey, thanks. I have not used Jekyll before and the docs where limited for docgen and I didnt know how to use it.

**Comment by msacco22** [comment]
Hi @frangio - you mind explaining briefly how to obtain HTML files just using the --templates CLI flag? I'm updating the contract.hbs file but still, the output is a .md markdown file. Thankyou!

**Comment by frangio** [comment]
@msacco22 Sure, sorry for the delay! If you do have an HTML template, I think what you're missing is using the `--extension`/`-x` option, because it has a default of `md`. So `-x html` will give you an html extension. Additionally, I think you will want to use the `--contract-pages` flag, to render one file per contract.

As for the template, here's an example in case anyone is looking for that:

```html
<!doctype html>
<html>
<!-- A <head> should go here. -->
<body>
<h1>{{name}}</h1>

<h2>Functions<h2>

{{#ownFunctions}}
<h3><code>{{signature}}</code></h3>

{{{natspec.userdoc}}}

{{/ownFunctions}}
</body>
</html>
```

Once thing that's important to keep in mind is that your NatSpec comments will have to be written in HTML as well, because they'll be inlined here. (Note the use of `{{{ ... }}}` tags to disable HMTL escaping in `{{{natspec.userdoc}}}`.) This is why I generally recommend outputting Markdown and using a site generator to process it into HTML.
